# Generated by Django 4.2 on 2025-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_added_at_cart_created_at_remove_cart_product_and_more'),
        ('product', '0002_product_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='product_set', to='cart.cart'),
        ),
    ]
