# Generated by Django 4.2 on 2025-07-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_user'),
        ('product', '0003_alter_product_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(related_name='product_carts', to='cart.cart'),
        ),
    ]
