# Generated by Django 4.2 on 2025-07-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_contact_number_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='pin_code',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
