# Generated by Django 4.2 on 2025-07-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_city_order_pin_code_order_shipping_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
