# Generated by Django 4.2 on 2025-07-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_product'),
        ('orders', '0005_alter_order_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='orders_items', to='cart.cart'),
        ),
    ]
