# Generated by Django 4.2 on 2025-07-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_options_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_items',
            new_name='cart',
        ),
    ]
