# Generated by Django 4.2 on 2025-07-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cartitem_options'),
        ('orders', '0011_alter_order_options_alter_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cart.cartitem'),
        ),
    ]
