# Generated by Django 4.2 on 2025-07-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
    ]
